In [15]:
import timeit
import numpy as np

In [ ]:
numRows = 300
numCols = 500
numIter = 1000

In [4]:
timeit.timeit("sum(range(1000))")

7.892576199956238

In [6]:
timeit.timeit("sum(range(1000))", number=1000)

0.007995499996468425

In [24]:
timeOnes = timeit.timeit(lambda: np.ones((numRows, numCols)), number=numIter)
print(timeOnes)
timeEmpty = timeit.timeit(lambda:np.empty((numRows, numCols)), number=numIter)
print(timeEmpty)

if timeOnes < timeEmpty:
    print(f'Generating array of ones is {timeEmpty / timeOnes} times faster!')
else:
    print(f'Generating empty array is {timeOnes / timeEmpty} times faster!')

0.033904799958691
0.001065799966454506
Generating empty array is 31.811597884994153 times faster!


In [26]:
%timeit np.zeros(shape = (numRows, numCols))
%timeit np.full(shape=(numRows, numCols), fill_value=0.0)

10 μs ± 179 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
323 μs ± 3.67 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
list_of_integers = [x for x in range(1000)]
%timeit np.random.choice(list_of_integers, size=1, replace=False)

rng = np.random.default_rng() # creating of generator
%timeit rng.choice(list_of_integers, size=1, replace=False)


56.1 μs ± 762 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
42.6 μs ± 640 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [78]:
mA = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(mA)
print(mA.ndim)
print(mA[0])
print(mA[0, 0])
print(mA[0, :])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[1 2 3 4]
1
[1 2 3 4]


In [ ]:
mB = mA[:2, 1:3] #mB is a view on mA, so changing of mB will change mA
# equal in data structures creates view, to make mA inmutable make a copy mB = mA.copy()
print(mB)
mB[0, 0] = 20
print(mA)

[[2 3]
 [6 7]]
[[ 1 20  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [80]:
mA[[1, 2], [1, 3]]

array([ 6, 12])

In [81]:
mA[::-1, :]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [82]:
mA.ndim

2

In [85]:
bool_slice = mA[mA % 2 == 0] # bullian conditions on array will give a vector
print(bool_slice)
print(bool_slice.ndim)

[ 2  4  6  8 10 12]
1


In [86]:
mA.data.contiguous

True

In [87]:
mB.data.contiguous

False

In [89]:
mB_flat = mB.flat.copy()
mB_flat.data.contiguous

True

In [97]:
vL = np.arange(9)

In [ ]:
mL_orederedC = vL.reshape((3, 3), order = 'C').copy()
mL_orederedC

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
mL_orderedF = vL.reshape((3, 3), order='F').copy()
mL_orderedF

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [114]:
np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]]) + np.array([10, 11, 12]).T

array([[11, 12, 13],
       [11, 12, 13],
       [11, 12, 13]])

In [132]:
mA_shape = (1000, 1000)
mR_shape = (100, 100)

mA = np.random.randn(*mA_shape)
mR = np.zeros((100, 100))

In [133]:
%%timeit
for ii, rows in enumerate(range(0, mA_shape[0], 10)):
    for jj, cols in enumerate(range(0, mA_shape[1], 10)):
        mR[ii, jj] = np.mean(mA[rows : rows + 10,cols : cols + 10])

31.9 ms ± 581 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [119]:
print(mR[0,1])

-0.0897220655515463


In [120]:
print(np.mean(mA[0:10, 10:20]))

-0.0897220655515463
